UPDATE `user`
SET `name` =
  (CASE abs(random() % 15)
    WHEN 0 THEN 'Azure'
    WHEN 1 THEN 'Cobalt'
    WHEN 2 THEN 'Copper'
    WHEN 3 THEN 'Crimson'
    WHEN 4 THEN 'Ember'
    WHEN 5 THEN 'Iron'
    WHEN 6 THEN 'Ivory'
    WHEN 7 THEN 'Lunar'
    WHEN 8 THEN 'Nova'
    WHEN 9 THEN 'Obsidian'
    WHEN 10 THEN 'Silent'
    WHEN 11 THEN 'Silver'
    WHEN 12 THEN 'Solar'
    WHEN 13 THEN 'Storm'
    ELSE 'Void'
  END) || '-' ||
  (CASE abs(random() % 23)
    WHEN 0 THEN 'Aegis'
    WHEN 1 THEN 'Atlas'
    WHEN 2 THEN 'Aurora'
    WHEN 3 THEN 'Beacon'
    WHEN 4 THEN 'Comet'
    WHEN 5 THEN 'Corsair'
    WHEN 6 THEN 'Drifter'
    WHEN 7 THEN 'Eclipse'
    WHEN 8 THEN 'Halcyon'
    WHEN 9 THEN 'Horizon'
    WHEN 10 THEN 'Kestrel'
    WHEN 11 THEN 'Nomad'
    WHEN 12 THEN 'Orion'
    WHEN 13 THEN 'Pulsar'
    WHEN 14 THEN 'Raven'
    WHEN 15 THEN 'Rook'
    WHEN 16 THEN 'Sentinel'
    WHEN 17 THEN 'Specter'
    WHEN 18 THEN 'Talon'
    WHEN 19 THEN 'Tempest'
    WHEN 20 THEN 'Viper'
    WHEN 21 THEN 'Wraith'
    ELSE 'Zenith'
  END) || '-' || printf('%03d', 100 + abs(random() % 900))
WHERE `display_name_set` = false;
